export default {
  SET_MOVIES: "SET_MOVIES",
  CURRENT_PAGE: "CURRENT_PAGE",
  TOGGLE_LOADER: "TOGGLE_LOADER",
  REMOVE_MOVIE: "REMOVE_MOVIE",
  TOGGLE_SEARCH: "TOGGLE_SEARCH",
  PUSH_MESSAGE_TOAST: "PUSH_MESSAGE_TOAST",
  TOGGLE_LOGIN: "TOGGLE_LOGIN",
};
